export const nationalities = [
  "Afgana",
  "Alemana",
  "Americana",
  "Andorrana",
  "Angoleña",
  "Antiguana",
  "Argentina",
  "Armenia",
  "Australiana",
  "Austriaca",
  "Azerí",
  "Bahameña",
  "Bangladesí",
  "Barbadiana",
  "Baréiní",
  "Belarusa",
  "Belga",
  "Beliceña",
  "Beninesa",
  "Bermudeña",
  "Bielorrusa",
  "Birmana",
  "Boliviana",
  "Bosnia",
  "Brasileña",
  "Británica",
  "Brunéi",
  "Búlgara",
  "Burundesa",
  "Butanesa",
  "Caboverdiana",
  "Camboyana",
  "Camerunesa",
  "Canadiense",
  "Catarí",
  "Centroafricana",
  "Chadiana",
  "Checa",
  "Chilena",
  "China",
  "Chipriota",
  "Colombiana",
  "Comorense",
  "Congoleña",
  "Costarricense",
  "Croata",
  "Cubana",
  "Danesa",
  "Dominicana",
  "Ecuatoguineana",
  "Ecuatoriana",
  "Egipcia",
  "Emiratí",
  "Eritrea",
  "Escocesa",
  "Eslovaca",
  "Eslovena",
  "Española",
  "Estoniana",
  "Etíope",
  "Feroesa",
  "Filipina",
  "Finlandesa",
  "Fiyiana",
  "Francesa",
  "Gabonesa",
  "Galesa",
  "Gambiana",
  "Georgiana",
  "Ghanesa",
  "Granadina",
  "Griega",
  "Groenlandesa",
  "Guatemalteca",
  "Guineana",
  "Guineana Ecuatorial",
  "Guyanesa",
  "Haitiana",
  "Holandesa",
  "Hondureña",
  "Hongkonesa",
  "Húngara",
  "India",
  "Indonesa",
  "Inglesa",
  "Iraní",
  "Iraquí",
  "Irlandesa",
  "Islandesa",
  "Israelí",
  "Italiana",
  "Jamaicana",
  "Japonesa",
  "Jordana",
  "Kazaja",
  "Keniana",
  "Kirguisa",
  "Kiribatiana",
  "Kuwaití",
  "Laosiana",
  "Lesotense",
  "Letona",
  "Libanesa",
  "Liberiana",
  "Libia",
  "Liechtensteiniano",
  "Lituana",
  "Luxemburguesa",
  "Macaense",
  "Macedonia",
  "Malasia",
  "Malauí",
  "Maldiva",
  "Malgache",
  "Malí",
  "Maltesa",
  "Marfileña",
  "Marroquí",
  "Martiniquesa",
  "Mauriciana",
  "Mauritana",
  "Mexicana",
  "Micronesia",
  "Moldava",
  "Monegasca",
  "Mongola",
  "Montenegrina",
  "Mozambiqueña",
  "Namibia",
  "Nauruana",
  "Nepalí",
  "Neozelandesa",
  "Nicaragüense",
  "Nigeriana",
  "Norcoreana",
  "Noruega",
  "Omana",
  "Pakistaní",
  "Palauana",
  "Palestina",
  "Panameña",
  "Papú",
  "Paraguaya",
  "Peruana",
  "Polaca",
  "Portuguesa",
  "Puertorriqueña",
  "Qatarí",
  "Ruandesa",
  "Rumana",
  "Rusa",
  "Saharaui",
  "Salomonense",
  "Salvadoreña",
  "Samoana",
  "Sanmarinense",
  "Santalucense",
  "Santo Tomense",
  "Saudí",
  "Senegalesa",
  "Serbia",
  "Seychellense",
  "Sierra Leonesa",
  "Singapurense",
  "Siria",
  "Somalí",
  "Sri Lanka",
  "Sudáfricana",
  "Sudanesa",
  "Sueca",
  "Suiza",
  "Surcoreana",
  "Surinamesa",
  "Swazilandesa",
  "Tailandesa",
  "Taiwanesa",
  "Tanzana",
  "Tayika",
  "Timorense",
  "Togolesa",
  "Tongana",
  "Trinidadiana",
  "Tunisina",
  "Turca",
  "Turkmena",
  "Tuvaluana",
  "Ucraniana",
  "Ugandesa",
  "Uruguaya",
  "Uzbeka",
  "Vanuatuense",
  "Venezolana",
  "Vietnamita",
  "Yemení",
  "Yibutiana",
  "Zambia",
  "Zimbabuense",
];

export const commonNationalities = [
  { value: "afghan", label: "Afgano/a" },
  { value: "albanian", label: "Albanés/esa" },
  { value: "algerian", label: "Argelino/a" },
  { value: "american", label: "Estadounidense" },
  { value: "argentine", label: "Argentino/a" },
  { value: "australian", label: "Australiano/a" },
  { value: "austrian", label: "Austriaco/a" },
  { value: "bangladeshi", label: "Bangladesí" },
  { value: "belgian", label: "Belga" },
  { value: "brazilian", label: "Brasileño/a" },
  { value: "british", label: "Británico/a" },
  { value: "bulgarian", label: "Búlgaro/a" },
  { value: "canadian", label: "Canadiense" },
  { value: "chinese", label: "Chino/a" },
  { value: "colombian", label: "Colombiano/a" },
  { value: "croatian", label: "Croata" },
  { value: "cuban", label: "Cubano/a" },
  { value: "czech", label: "Checo/a" },
  { value: "danish", label: "Danés/esa" },
  { value: "dutch", label: "Holandés/esa" },
  { value: "egyptian", label: "Egipcio/a" },
  { value: "english", label: "Inglés/esa" },
  { value: "estonian", label: "Estonio/a" },
  { value: "finnish", label: "Finlandés/esa" },
  { value: "french", label: "Francés/esa" },
  { value: "german", label: "Alemán/mana" },
  { value: "greek", label: "Griego/a" },
  { value: "honduran", label: "Hondureño/a" },
  { value: "hungarian", label: "Húngaro/a" },
  { value: "icelandic", label: "Islandés/esa" },
  { value: "indian", label: "Indio/a" },
  { value: "indonesian", label: "Indonesio/a" },
  { value: "iranian", label: "Iraní" },
  { value: "iraqi", label: "Iraquí" },
  { value: "irish", label: "Irlandés/esa" },
  { value: "israeli", label: "Israelí" },
  { value: "italian", label: "Italiano/a" },
  { value: "japanese", label: "Japonés/esa" },
  { value: "jordanian", label: "Jordano/a" },
  { value: "kenyan", label: "Keniano/a" },
  { value: "korean", label: "Coreano/a" },
  { value: "kuwaiti", label: "Kuwaití" },
  { value: "lebanese", label: "Libanés/esa" },
  { value: "malaysian", label: "Malasio/a" },
  { value: "mexican", label: "Mexicano/a" },
  { value: "moroccan", label: "Marroquí" },
  { value: "new_zealander", label: "Neozelandés/esa" },
  { value: "nigerian", label: "Nigeriano/a" },
  { value: "norwegian", label: "Noruego/a" },
  { value: "pakistani", label: "Pakistani" },
  { value: "palestinian", label: "Palestino/a" },
  { value: "peruvian", label: "Peruano/a" },
  { value: "polish", label: "Polaco/a" },
  { value: "portuguese", label: "Portugués/esa" },
  { value: "romanian", label: "Rumano/a" },
  { value: "russian", label: "Ruso/a" },
  { value: "saudi_arabian", label: "Saudita" },
  { value: "scottish", label: "Escocés/esa" },
  { value: "serbian", label: "Serbio/a" },
  { value: "singaporean", label: "Singapurense" },
  { value: "slovak", label: "Eslovaco/a" },
  { value: "slovenian", label: "Esloveno/a" },
  { value: "south_african", label: "Sudafricano/a" },
  { value: "spanish", label: "Español/a" },
  { value: "swedish", label: "Sueco/a" },
  { value: "swiss", label: "Suizo/a" },
  { value: "syrian", label: "Sirio/a" },
  { value: "taiwanese", label: "Taiwanés/esa" },
  { value: "thai", label: "Tailandés/esa" },
  { value: "tunisian", label: "Tunecino/a" },
  { value: "turkish", label: "Turco/a" },
  { value: "ukrainian", label: "Ucraniano/a" },
  { value: "uruguayan", label: "Uruguayo/a" },
  { value: "venezuelan", label: "Venezolano/a" },
  { value: "vietnamese", label: "Vietnamita" },
  { value: "welsh", label: "Galés/esa" },
  // Agrega más nacionalidades aquí
];
