const pacientes = [
    {
      date: '2023-07-01',
      patient: 'Juan Pérez',
      services: ['Consulta médica', 'Análisis de sangre'],
      payMethod: 'Tarjeta de crédito',
      currency: 'ARS',
      amount: 1500,
      usd: 15,
    },
    {
      date: '2023-07-02',
      patient: 'María Gómez',
      services: ['Radiografía', 'Ecografía'],
      payMethod: 'Efectivo',
      currency: 'ARS',
      amount: 2000,
      usd: 20,
    },
    {
      date: '2023-07-03',
      patient: 'Luis Rodríguez',
      services: ['Consulta médica', 'Análisis de sangre', 'Radiografía'],
      payMethod: 'Transferencia bancaria',
      currency: 'ARS',
      amount: 2500,
      usd: 25,
    },
    {
      date: '2023-07-04',
      patient: 'Ana López',
      services: ['Ecografía', 'Análisis de sangre'],
      payMethod: 'Tarjeta de débito',
      currency: 'ARS',
      amount: 1800,
      usd: 18,
    },
    {
      date: '2023-07-05',
      patient: 'Carlos Fernández',
      services: ['Consulta médica', 'Ecografía'],
      payMethod: 'Efectivo',
      currency: 'ARS',
      amount: 2200,
      usd: 22,
    },
    {
      date: '2023-07-06',
      patient: 'Roberto Sánchez',
      services: ['Consulta médica'],
      payMethod: 'Transferencia bancaria',
      currency: 'ARS',
      amount: 1800,
      usd: 18,
    },
    // Agrega más pacientes con pagos en pesos argentinos aquí...
    {
      date: '2023-07-07',
      patient: 'Laura Torres',
      services: ['Ecografía'],
      payMethod: 'Efectivo',
      currency: 'ARS',
      amount: 1600,
      usd: 16,
    },
    {
      date: '2023-07-08',
      patient: 'Javier Díaz',
      services: ['Radiografía'],
      payMethod: 'Tarjeta de crédito',
      currency: 'ARS',
      amount: 1900,
      usd: 19,
    },
    {
      date: '2023-07-09',
      patient: 'Marcela Vargas',
      services: ['Consulta médica', 'Análisis de sangre', 'Ecografía'],
      payMethod: 'Efectivo',
      currency: 'ARS',
      amount: 2700,
      usd: 27,
    },
    {
      date: '2023-07-10',
      patient: 'Miguel González',
      services: ['Análisis de sangre', 'Radiografía'],
      payMethod: 'Transferencia bancaria',
      currency: 'ARS',
      amount: 2050,
      usd: 20.5,
    },
    {
      date: '2023-07-11',
      patient: 'Fernanda Silva',
      services: ['Consulta médica', 'Ecografía'],
      payMethod: 'Tarjeta de débito',
      currency:'ARS',
      amount: 1750,
      usd: 17.5,
    },
    {
      date: '2023-07-12',
      patient: 'Diego Rojas',
      services: ['Radiografía'],
      payMethod: 'Efectivo',
      currency: 'ARS',
      amount: 1900,
      usd: 19,
    },
    {
      date: '2023-07-13',
      patient: 'Carolina Paredes',
      services: ['Consulta médica', 'Análisis de sangre'],
      payMethod: 'Tarjeta de crédito',
      currency: 'ARS',
      amount: 1500,
      usd: 15,
    },
    {
      date: '2023-07-14',
      patient: 'Santiago Castro',
      services: ['Ecografía', 'Análisis de sangre'],
      payMethod: 'Efectivo',
      currency: 'ARS',
      amount: 1800,
      usd: 18,
    },
    {
      date: '2023-07-15',
      patient: 'Paula Morales',
      services: ['Consulta médica', 'Radiografía'],
      payMethod: 'Transferencia bancaria',
      currency: 'ARS',
      amount: 2200,
      usd: 22,
    },
    {
      date: '2023-07-16',
      patient: 'Andrés Herrera',
      services: ['Ecografía'],
      payMethod: 'Efectivo',
      currency: 'ARS',
      amount: 1600,
      usd: 16,
    },
    {
      date: '2023-07-17',
      patient: 'Natalia Fuentes',
      services: ['Consulta médica', 'Análisis de sangre', 'Ecografía'],
      payMethod: 'Tarjeta de crédito',
      currency: 'ARS',
      amount: 2500,
      usd: 25,
    },
    {
      date: '2023-07-18',
      patient: 'Gustavo Montenegro',
      services: ['Radiografía', 'Análisis de sangre'],
      payMethod: 'Efectivo',
      currency: 'ARS',
      amount: 1900,
      usd: 19,
    },
    {
      date: '2023-07-19',
      patient: 'Valeria Rojas',
      services: ['Consulta médica', 'Ecografía'],
      payMethod: 'Transferencia bancaria',
      currency: 'ARS',
      amount: 1800,
      usd: 18,
    },
    {
      date: '2023-07-20',
      patient: 'Alejandro Silva',
      services: ['Radiografía'],
      payMethod: 'Efectivo',
      currency: 'ARS',
      amount: 1900,
      usd: 19,
    },
  ];
  
  export default pacientes;
  