const defaultPatients = [
  {
      id: 2,
      name: "Enzo",
      surname: "Bustos Fierro",
      gender: "Male",
      dni: "",
      cellphone: "+54 9 3513 157284",
      email: "-",
      province: "Cordoba",
      city: "Cordoba Capital",
      address: "Mendoza 1664 (casa)",
      country: "Argentina",
      reference: "Pablo",
      relationship: "Father",
      referenceCellphone: "+54 9 3512 459943",
      birthDate: "18/1/2001",
      admissionDate: "27/3/2023",
      healthInsurance: "",
      insuranceNumber: "",
      socialSecurity: "",
      socialSecurityNumber: "",
      allergies: "-",
      diseases: "-",
      frequency: "Weekly",
      convienes: "",
      active: "Yes",
      cuil: "",
      currentPsychiatricMediation: "",
      psychiatrist: "",
      tags: ["pendiente"],
  },
  {
      id: 3,
      name: "Silvina",
      surname: "Durand",
      gender: "Female",
      dni: "",
      cellphone: "1160183782",
      email: "",
      province: "Buenos Aires",
      city: "Tigre",
      address: "Solis 1170",
      country: "Argentina",
      reference: "Manuel",
      relationship: "Son/Daughter",
      referenceCellphone: "1161310076",
      birthDate: "6/11/1965",
      admissionDate: "14/4/2023",
      healthInsurance: "Swiss Medical",
      insuranceNumber: "",
      socialSecurity: "",
      socialSecurityNumber: "0",
      allergies: "",
      diseases: "Hypertension, osteoarthritis",
      frequency: "Weekly",
      convienes: "3 children (Manuel, Lara, and Julián)",
      active: "Yes",
      cuil: "",
      currentPsychiatricMediation: "",
      psychiatrist: "",
      tags: ["cool"],
  },
  {
      id: 4,
      name: "Joaquín",
      surname: "Castro Montiel",
      gender: "Male",
      dni: "",
      cellphone: "+54 9 2291 513051",
      email: "",
      province: "Buenos Aires",
      city: "Miramar",
      address: "9 de julio 1390 (casa)",
      country: "Argentina",
      reference: "Dolores",
      relationship: "Sibling",
      referenceCellphone: "",
      birthDate: "6/5/1985",
      admissionDate: "6/4/2023",
      healthInsurance: "",
      insuranceNumber: "",
      socialSecurity: "",
      socialSecurityNumber: "0",
      allergies: "",
      diseases: "",
      frequency: "Weekly",
      convienes: "",
      active: "Yes",
      cuil: "",
      currentPsychiatricMediation: "",
      psychiatrist: "",
      tags: ["ausente con aviso"],
  },
  {
      id: 5,
      name: "Marcelo Nicolás",
      surname: "Radin",
      gender: "Male",
      dni: "",
      cellphone: "1168207391",
      email: "",
      province: "Buenos Aires",
      city: "Olivos",
      address: "D. Faustino Sarmiento 3250",
      country: "Argentina",
      reference: "Pamela",
      relationship: "Partner",
      referenceCellphone: "1155712715",
      birthDate: "14/7/1989",
      admissionDate: "3/4/2023",
      healthInsurance: "",
      insuranceNumber: "",
      socialSecurity: "",
      socialSecurityNumber: "0",
      allergies: "-",
      diseases: "-",
      frequency: "Weekly",
      convienes: "-",
      active: "Yes",
      cuil: "",
      currentPsychiatricMediation: "",
      psychiatrist: "",
      tags: ["pendiente"],
  },
  {
      id: 6,
      name: "Yamile María",
      surname: "Etala",
      gender: "Female",
      dni: "",
      cellphone: "+54 9 3444 621532",
      email: "",
      province: "Entre Ríos",
      city: "Gualeguay",
      address: "Alem 36",
      country: "Argentina",
      reference: "Silvia",
      relationship: "Mother",
      referenceCellphone: "+54 9 3444 497746",
      birthDate: "15/1/1997",
      admissionDate: "13/1/2023",
      healthInsurance: "OSDE",
      insuranceNumber: "",
      socialSecurity: "OSPER",
      socialSecurityNumber: "0",
      allergies: "",
      diseases: "",
      frequency: "Weekly",
      convienes: "Alone",
      active: "Yes",
      cuil: "",
      currentPsychiatricMediation: "",
      psychiatrist: "",
      tags: [],
  },
  {
      id: 7,
      name: "Antonella",
      surname: "Zanier",
      gender: "Female",
      dni: "",
      cellphone: "1168038375",
      email: "zanier.antonella@gmail.com",
      province: "Buenos Aires",
      city: "Lanús Oeste",
      address: "Doctor Melo 3144 5ºB",
      country: "Argentina",
      reference: "Patricia",
      relationship: "Mother",
      referenceCellphone: "1152603830",
      birthDate: "2/3/1991",
      admissionDate: "19/6/2020",
      healthInsurance: "MEDICUS",
      insuranceNumber: "",
      socialSecurity: "",
      socialSecurityNumber: "0",
      allergies: "",
      diseases: "",
      frequency: "Biweekly",
      convienes: "Alone",
      active: "Yes",
      cuil: "",
      currentPsychiatricMediation: "CBD cannabis oil",
      psychiatrist: "Dr. Yona Sandoval",
      tags: [],
  },
  {
      id: 8,
      name: "Martín Andrés",
      surname: "Corso",
      gender: "Male",
      dni: "",
      cellphone: "1135052168",
      email: "",
      province: "Buenos Aires",
      city: "Virrey del Pino, Matanza",
      address: "",
      country: "Argentina",
      reference: "Eduardo Hartman",
      relationship: "Partner",
      referenceCellphone: "1162444967",
      birthDate: "26/9/1985",
      admissionDate: "13/1/2023",
      healthInsurance: "OSDE 310",
      insuranceNumber: "",
      socialSecurity: "",
      socialSecurityNumber: "",
      allergies: "",
      diseases: "",
      frequency: "Weekly",
      convienes: "Spouse Eduardo",
      active: "Yes",
      cuil: "20-31896336-4",
      currentPsychiatricMediation: "Sertraline",
      psychiatrist: "Dr. Yona Sandoval",
      tags: [],
  },
  {
      id: 9,
      name: "Magalí",
      surname: "Blumberg",
      gender: "Female",
      dni: "",
      cellphone: "1161078131",
      email: "",
      province: "CABA",
      city: "CABA",
      address: "Margariños Cervantes 3043 2ºB",
      country: "Argentina",
      reference: "",
      relationship: "Mother",
      referenceCellphone: "1159797427",
      birthDate: "9/3/1991",
      admissionDate: "19/5/2022",
      healthInsurance: "OSESAC",
      insuranceNumber: "",
      socialSecurity: "",
      socialSecurityNumber: "0",
      allergies: "",
      diseases: "-",
      frequency: "-",
      convienes: "",
      active: "Biweekly",
      cuil: "",
      currentPsychiatricMediation: "",
      psychiatrist: "",
      tags: ["developer", "nice"],
  },
  {
      id: 10,
      name: "Agustín Fernando",
      surname: "Mirabelli",
      gender: "Male",
      dni: "",
      cellphone: "1158189315",
      email: "",
      province: "CABA",
      city: "CABA",
      address: "Fray Cayetano Rodriguez 879 (timbre planta alta)",
      country: "Argentina",
      reference: "Georgina / Juliana",
      relationship: "",
      referenceCellphone: "1140232206/1168910768",
      birthDate: "12/1/1984",
      admissionDate: "14/7/2020",
      healthInsurance: "SANCOR",
      insuranceNumber: "",
      socialSecurity: "",
      socialSecurityNumber: "0",
      allergies: "",
      diseases: "",
      frequency: "Weekly",
      convienes: "Alone (downstairs: sister Juliana)",
      active: "Yes",
      cuil: "",
      currentPsychiatricMediation: "",
      psychiatrist: "Escitalopram 20mg",
      tags: ["developer", "nice"],
  },
  {
      id: 11,
      name: "Renzo",
      surname: "Adamo",
      gender: "Male",
      dni: "",
      cellphone: "1126308819",
      email: "",
      province: "CABA",
      city: "CABA",
      address: "Avellaneda 1863 1ºD",
      country: "Argentina",
      reference: "",
      relationship: "Sibling",
      referenceCellphone: "1134577797",
      birthDate: "11/2/1985",
      admissionDate: "8/8/2019",
      healthInsurance: "ACCORD SALUD",
      insuranceNumber: "",
      socialSecurity: "",
      socialSecurityNumber: "0",
      allergies: "",
      diseases: "",
      frequency: "Weekly",
      convienes: "Alone",
      active: "Yes",
      cuil: "",
      currentPsychiatricMediation: "",
      psychiatrist: "Emergency medication: alprazolam",
      tags: ["developer", "nice"],
  },
  {
      id: 12,
      name: "Tatiana Isabel",
      surname: "Espinola",
      gender: "Female",
      dni: "",
      cellphone: "1164475432",
      email: "",
      province: "Buenos Aires",
      city: "Avellaneda",
      address: "",
      country: "Argentina",
      reference: "Karina",
      relationship: "Sibling",
      referenceCellphone: "1160552965",
      birthDate: "16/11/1993",
      admissionDate: "1/9/2018",
      healthInsurance: "SWISS MEDICAL",
      insuranceNumber: "",
      socialSecurity: "",
      socialSecurityNumber: "0",
      allergies: "-",
      diseases: "",
      frequency: "",
      convienes: "-",
      active: "Biweekly",
      cuil: "",
      currentPsychiatricMediation: "",
      psychiatrist: "",
      tags:["developer", "nice"],
  },
  {
      id: 13,
      name: "Camila",
      surname: "Becker Onofre",
      gender: "Female",
      dni: "",
      cellphone: "+54 9 2213 801568",
      email: "",
      province: "Buenos Aires",
      city: "Carmen de Areco",
      address: "Ignacio Canal 1104",
      country: "Argentina",
      reference: "Fabiana Furch",
      relationship: "Mother",
      referenceCellphone: "+54 9 2273 404204",
      birthDate: "14/3/1995",
      admissionDate: "1/12/2022",
      healthInsurance: "IOMA",
      insuranceNumber: "",
      socialSecurity: "",
      socialSecurityNumber: "0",
      allergies: "",
      diseases: "",
      frequency: "",
      convienes: "Bipolar Disorder I",
      active: "Biweekly",
      cuil: "",
      currentPsychiatricMediation: "",
      psychiatrist: "Aripiprazole 10mg/d and Lamotrigine 200mg/d",
      tags: ["developer", "nice"],
  },
  {
      id: 14,
      name: "Diamela Azul",
      surname: "Raposo",
      gender: "Female",
      dni: "",
      cellphone: "+54 9 2257 406139",
      email: "",
      province: "CABA",
      city: "CABA",
      address: "Hidalgo 1533",
      country: "Argentina",
      reference: "",
      relationship: "Mother",
      referenceCellphone: "+54 9 2257 638266",
      birthDate: "23/1/1998",
      admissionDate: "17/10/2022",
      healthInsurance: "IOMA",
      insuranceNumber: "",
      socialSecurity: "",
      socialSecurityNumber: "0",
      allergies: "",
      diseases: "",
      frequency: "Weekly",
      convienes: "Alone",
      active: "Yes",
      cuil: "27-40795143-9",
      currentPsychiatricMediation: "",
      psychiatrist: "Dr. Mariángeles Diaz",
      tags:["developer", "nice"],
  },
  {
      id: 15,
      name: "Juan Pablo",
      surname: "Santoro",
      gender: "Male",
      dni: "0",
      cellphone: "1165413193",
      email: "",
      province: "CABA",
      city: "CABA",
      address: "Bering 2619 7ºA",
      country: "Argentina",
      reference: "Tomás",
      relationship: "Sibling",
      referenceCellphone: "+34677422550",
      birthDate: "10/11/1983",
      admissionDate: "9/3/2023",
      healthInsurance: "OSDE",
      insuranceNumber: "",
      socialSecurity: "",
      socialSecurityNumber: "0",
      allergies: "",
      diseases: "Type 1 Diabetes",
      frequency: "Weekly",
      convienes: "Partner Ana Clara",
      active: "Yes",
      cuil: "",
      currentPsychiatricMediation: "",
      psychiatrist: "",
      tags: ["developer", "nice"],
  },
  {
      id: 16,
      name: "Lady Nathaly",
      surname: "Pulido Arbelaez",
      gender: "Female",
      dni: "",
      cellphone: "+57 305 7329354",
      email: "",
      province: "Bogotá (Las Cruces)",
      city: "Calle 1ºD Nº545 depto 2",
      country: "Colombia",
      reference: "Paula Scheps",
      relationship: "Friend",
      referenceCellphone: "",
      birthDate: "3/6/1995",
      admissionDate: "31/5/2023",
      healthInsurance: "",
      insuranceNumber: "",
      socialSecurity: "",
      socialSecurityNumber: "0",
      allergies: "",
      diseases: "Migraines, Irritable Bowel Syndrome, Polycystic Ovary Syndrome",
      frequency: "Weekly",
      convienes: "Parents and sister",
      active: "Yes",
      cuil: "",
      currentPsychiatricMediation: "",
      psychiatrist: "",
      tags: ["holis"],
  },
  {
      id: 17,
      name: "",
      surname: "",
      gender: "0",
      dni: "",
      cellphone: "",
      email: "",
      province: "",
      city: "",
      address: "",
      country: "",
      reference: "",
      relationship: "",
      referenceCellphone: "",
      birthDate: "",
      admissionDate: "",
      healthInsurance: "",
      insuranceNumber: "",
      socialSecurity: "",
      socialSecurityNumber: "",
      allergies: "",
      diseases: "",
      frequency: "0",
      convienes: "",
      active: "Yes",
      cuil: "",
      currentPsychiatricMediation: "Sertraline",
      psychiatrist: "Dr. Yona Sandoval",
      tags: ["developer", "nice"],
  },
  {
      id: 18,
      name: "Milagros",
      surname: "Marchese",
      gender: "Female",
      dni: "",
      cellphone: "1131485916",
      email: "milagrosmarchese1@gmail.com",
      province: "Buenos Aires",
      city: "Canning",
      address: "Juana de Arco 6100",
      country: "Argentina",
      reference: "Marina",
      relationship: "Mother",
      referenceCellphone: "1153206928",
      birthDate: "21/5/2004",
      admissionDate: "5/6/2023",
      healthInsurance: "",
      insuranceNumber: "",
      socialSecurity: "",
      socialSecurityNumber: "0",
      allergies: "",
      diseases: "",
      frequency: "Weekly",
      convienes: "Mother Marina",
      active: "No",
      cuil: "",
      currentPsychiatricMediation: "",
      psychiatrist: "",
      tags: ["developer", "nice"],
  }
];

export default defaultPatients;
